services:

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    volumes:
      - .:/var/www
    depends_on:
      - db
      - mongodb
    networks:
      - app-network
    environment:
      DATABASE_URL: "postgresql://postgresql_user:postgreSQL_dev_2026@db:5432/vite_gourmand?serverVersion=16&charset=utf8"
      MONGODB_URI: "mongodb://mongoDB_user:mongoDB_dev_2026@mongodb:27017"
      MONGODB_DBNAME: vite_gourmand

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
    networks:
      - app-network

  ###> doctrine/doctrine-bundle ###
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vite_gourmand
      POSTGRES_PASSWORD: postgreSQL_dev_2026
      POSTGRES_USER: postgresql_user
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-d", "vite_gourmand", "-U", "postgresql_user" ]
      timeout: 5s
      retries: 5
      start_period: 60s
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data:rw
    networks:
      - app-network
  ###< doctrine/doctrine-bundle ###

  ###> doctrine/mongodb-odm-bundle ###
  mongodb:
    image: mongo:7
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoDB_user
      MONGO_INITDB_ROOT_PASSWORD: mongoDB_dev_2026
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoDB_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoDB_dev_2026
      ME_CONFIG_MONGODB_URL: mongodb://mongoDB_user:mongoDB_dev_2026@mongodb:27017/
      ME_CONFIG_BASICAUTH: "false"
    depends_on:
      - mongodb
    networks:
      - app-network
  ###< doctrine/mongodb-odm-bundle ###

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data:
