<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260213151418 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Suppression de la table horaire (migrée vers MongoDB)';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('DROP TABLE horaire');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('CREATE TABLE horaire (horaire_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(50) NOT NULL, heure_ouverture VARCHAR(50) NOT NULL, heure_fermeture VARCHAR(50) NOT NULL, PRIMARY KEY (horaire_id))');
    }
}
