<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260203192319 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE allergene (allergene_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) NOT NULL, PRIMARY KEY (allergene_id))');
        $this->addSql('CREATE TABLE avis (avis_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, note VARCHAR(50) NOT NULL, description VARCHAR(50) NOT NULL, statut VARCHAR(50) NOT NULL, PRIMARY KEY (avis_id))');
        $this->addSql('CREATE TABLE commande (numero_commande VARCHAR(50) NOT NULL, date_commande DATE NOT NULL, date_prestation DATE NOT NULL, heure_livraison VARCHAR(50) NOT NULL, nombre_personne INT NOT NULL, prix_livraison DOUBLE PRECISION NOT NULL, statut VARCHAR(50) NOT NULL, pret_materiel BOOLEAN NOT NULL, restitution_materiel BOOLEAN NOT NULL, PRIMARY KEY (numero_commande))');
        $this->addSql('CREATE TABLE horaire (horaire_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, jour VARCHAR(50) NOT NULL, heure_ouverture VARCHAR(50) NOT NULL, heure_fermeture VARCHAR(50) NOT NULL, PRIMARY KEY (horaire_id))');
        $this->addSql('CREATE TABLE menu (menu_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre VARCHAR(50) NOT NULL, nombre_personne_minimum INT NOT NULL, prix_par_personne DOUBLE PRECISION NOT NULL, regime VARCHAR(50) NOT NULL, description VARCHAR(50) NOT NULL, quantite_restante INT NOT NULL, PRIMARY KEY (menu_id))');
        $this->addSql('CREATE TABLE plat (plat_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, titre_plat VARCHAR(50) NOT NULL, photo BYTEA NOT NULL, PRIMARY KEY (plat_id))');
        $this->addSql('CREATE TABLE regime (regime_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) NOT NULL, PRIMARY KEY (regime_id))');
        $this->addSql('CREATE TABLE role (role_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) NOT NULL, PRIMARY KEY (role_id))');
        $this->addSql('CREATE TABLE theme (theme_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, libelle VARCHAR(50) NOT NULL, PRIMARY KEY (theme_id))');
        $this->addSql('CREATE TABLE "utilisateur" (utilisateur_id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(50) NOT NULL, prenom VARCHAR(50) NOT NULL, telephone VARCHAR(50) NOT NULL, ville VARCHAR(50) NOT NULL, pays VARCHAR(50) NOT NULL, adresse_postale VARCHAR(50) NOT NULL, PRIMARY KEY (utilisateur_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_IDENTIFIER_EMAIL ON "utilisateur" (email)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE allergene');
        $this->addSql('DROP TABLE avis');
        $this->addSql('DROP TABLE commande');
        $this->addSql('DROP TABLE horaire');
        $this->addSql('DROP TABLE menu');
        $this->addSql('DROP TABLE plat');
        $this->addSql('DROP TABLE regime');
        $this->addSql('DROP TABLE role');
        $this->addSql('DROP TABLE theme');
        $this->addSql('DROP TABLE "utilisateur"');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
